### ISSUE TITLE
Missing C API

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_spi#47]
No C API so must currently be accessed via XC using interfaces.

I believe @mbruno-xmos is working on a pure C version with a function call interface. Once merged, this can be closed.

**Comment by mbruno-xmos** [comment]
https://github.com/xmos/lib_spi/tree/feature/c_api

We have no intention to merge this into master/main/develop. It is not backwards compatible and does not co-exist. It will either live in that branch forever or be moved to another repository.

**Comment by mbanth** [comment]
I am closing this issue because the creation of an SPI module in the xCore SDK has rendered the inclusion of a C API in this repository redundant.
