### ISSUE TITLE
Missing xCore test

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_spi#48]
The majority of tests are done on XS2 using xmostest. The test files are built for XS3 (to check for build errors) but not executed.
The SPI master AN00160 is run on the AI explorer board and talks to real HW. 
The SPI slave AN00161 is not properly on the AI explorer board as it has no HW to support this. It is built however and xrun (with no --io) to check it is a valid XS3 executable.

**Comment by ACascarino** [comment]
@ed-xmos your commit on this has in my opinion closed the headline, but I'm raising another issue to port these tests away from xmostest
