### ISSUE TITLE
Missing file for the xcommon_cmake build system

### ISSUE THREAD

**Issue by mfreeborn** [xmos/lib_spi#66]
I'm trying to start a new project using up to date best-practices, which seems to include the xcommon_cmake build system. Other libraries like `lib_i2c` have a `lib_build_info.cmake`, but `lib_spi` doesn't. Please could such a file be added so I don't have to keep manually doing it on my end with each new project?

**Comment by mfreeborn** [comment]
I wonder if a new release would be merited - this looks like it's still only available on the `develop` branch.

**Comment by kubapilch** [comment]
For anyone waiting till a full release is there, a specific commit hash can be used in the `deps.cmake` file to reference a specific commit from `develop` branch which is compatible with XCommon CMake.

```
set(APP_DEPENDENT_MODULES "lib_spi(eacb1cd)")
```
